captainVersion: 4
services:
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: $$cap_pg_user
            POSTGRES_PASSWORD: $$cap_pg_pass
            POSTGRES_DB: $$cap_pg_db
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: christopherkapic/strapi-ck:$$cap_strapi-ck_version
        volumes:
            - $$cap_appname-data:/srv/app
        restart: always
        environment:
            HOST: 0.0.0.0
            PORT: 1337
            APP_KEYS: "Y1zrc6x3l6xT/upTRJnBEQ==,75yWo3mw+fg0g5Ge5c2upQ==,/LrryMqxJjQQ+vRrox/uxw==,0lBqtiYIfEDdAouuwOdtxA=="
            JWT_SECRET: $$cap_strapi_jwt_secret
            API_TOKEN_SALT: $$cap_api_token_salt
            CLOUDINARY_NAME: $$cap_cloudinary_name
            CLOUDINARY_KEY: $$cap_cloudinary_key
            CLOUDINARY_SECRET: $$cap_cloudinary_secret
            DATABASE_HOST: srv-captain--$$cap_appname-db
            DATABASE_PORT: $$cap_pg_port
            DATABASE_NAME: $$cap_pg_db
            DATABASE_USERNAME: $$cap_pg_user
            DATABASE_PASSWORD: $$cap_pg_pass
            DATABASE_SSL: False
            POSTGRESQL_USER: $$cap_pg_user
            POSTGRESQL_PASSWORD: $$cap_pg_pass
            POSTGRESQL_HOST: srv-captain--$$cap_appname-db
            POSTGRESQL_PORT: 5432
            POSTGRESQL_DATABASE_NAME: $$cap_pg_db
        caproverExtra:
            containerHttpPort: 1337
caproverOneClickApp:
    variables:
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: 14.2
          description: Choose the latest version of Postgres from https://hub.docker.com/_/postgres?tab=tags
        - id: $$cap_strapi-ck_version
          label: Strapi-ck Version
          description: Choose the latest version of Strapi-ck from https://hub.docker.com/r/christopherkapic/strapi-ck?tab=tags
          defaultValue: latest
        - id: $$cap_pg_user
          label: Postgres Username
          description: ''
          validRegex: /.{1,}/
          defaultValue: strapi
        - id: $$cap_pg_pass
          label: Postgres Password
          description: ''
          validRegex: /.{1,}/
          defaultValue: $$cap_gen_random_hex(32)
        - id: $$cap_pg_port
          label: Postgres Port
          description: ''
          validRegex: /.{1,}/
          defaultValue: 5432
        - id: $$cap_pg_db
          label: Postgres Default Database
          description: ''
          validRegex: /.{1,}/
          defaultValue: strapi
        - id: $$cap_strapi_jwt_secret
          label: JWT Secret
          description: ''
          validRegex: /.{1,}/
          defaultValue: $$cap_gen_random_hex(32)
        - id: $$cap_api_token_salt
          label: API Token Salt
          description: ''
          validRegex: /.{1,}/
          defaultValue: $$cap_gen_random_hex(32)
        - id: $$cap_cloudinary_name
          label: Cloudinary Name
          description: ''
        - id: $$cap_cloudinary_key
          label: Cloudinary Key
          description: ''
        - id: $$cap_cloudinary_secret
          label: Cloudinary Secret
          description: ''
       
    instructions:
        start: |-
            Strapi is an open source headless CMS. This is Christopher Kapic's modified version.
            More details: https://github.com/christopher-kapic/strapi-ck
        end: |-
            Strapi-ck has been successfully deployed!
    displayName: Strapi-CK
    isOfficial: true
    description: Strapi is an open source headless CMS. This is Christopher Kapic's modified version.
    documentation: See https://github.com/christopher-kapic/strapi-ck
