captainVersion: 4
services:
    # GoTrue
    $$cap_appname:
        image: supabase/gotrue:$$cap_gotrue_version
        # ports:
        #     - ${AUTH_PORT}
        depends_on:
            - $$cap_appname-db
        restart: always
        environment:
            GOTRUE_JWT_SECRET: $$cap_jwt_secret
            GOTRUE_JWT_EXP: 3600
            GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
            GOTRUE_DB_DRIVER: postgres
            DB_NAMESPACE: auth
            # API_EXTERNAL_URL: http://localhost:8000
            GOTRUE_API_HOST: 0.0.0.0
            PORT: 9999

            GOTRUE_SMTP_HOST: ${SMTP_HOST}
            GOTRUE_SMTP_PORT: ${SMTP_PORT}
            GOTRUE_SMTP_USER: ${SMTP_USER}
            GOTRUE_SMTP_PASS: ${SMTP_PASS}
            GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}

            GOTRUE_DISABLE_SIGNUP: 'false'
            GOTRUE_SITE_URL: http://localhost:8000
            GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
            GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
            GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
            GOTRUE_MAILER_AUTOCONFIRM: 'true'
            GOTRUE_LOG_LEVEL: DEBUG
            GOTRUE_OPERATOR_TOKEN: ${OPERATOR_TOKEN}
            DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/postgres?sslmode=disable'
        caproverExtra:
            containerHttpPort: 9999
    $$cap_appname-db:
        image: postgres:13.3
caproverOneClickApp:
    variables:
        - id: $$cap_gotrue_version
          label: GoTrue Version
          description: Choose the latest from https://hub.docker.com/r/supabase/gotrue/tags
          defaultValue: v2.0.7
          validRegex: /^v([0-9]+(\.[0-9]+)+)$/
        - id: $$cap_postgres_version
          label: Postgres Version
          description: Choose the latest from https://hub.docker.com/_/postgres?tab=tags
          validRegex: /^([0-9]+(\.[0-9]+)+)$/
          defaultValue: 13.4
        - id: '$$cap_site_url'
          label: SITE_URL
          description: The base URL at which your site is located.
          validRegex: /^[a-zA-Z]+://([a-zA-Z]+(\.[a-zA-Z]+)+)$/
        - id: $$cap_jwt_secret
          label: JWT Secret
          description: A 32+ character string (do not expose in version control)
          defaultValue: $$cap_gen_random_hex(32)
        
    instructions:
        start: |-
            GoTrue is an API developed by Netlify to handle user authentication. This is the version used by supabase.io, which tends to have faster development than Netlify's version.
            More details: https://github.com/supabase/gotrue
        end: |-
            GoTrue has been successfully deployed!
    displayName: "[WIP] Supabase GoTrue"
    isOfficial: false
    description: An open source authentication system developed by Netlify, forked by Supabase.
    documentation: See https://github.com/supabase/gotrue
