captainVersion: 4
services:
    # GoTrue
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: supabase/gotrue:latest
        environment: # Need to finish, currently from supabase's docker-compose
            GOTRUE_JWT_SECRET: ${JWT_SECRET}
            GOTRUE_JWT_EXP: 3600
            GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
            GOTRUE_DB_DRIVER: postgres
            DB_NAMESPACE: auth
            API_EXTERNAL_URL: localhost
            GOTRUE_API_HOST: 0.0.0.0
            PORT: ${AUTH_PORT}

            GOTRUE_SMTP_HOST: ${SMTP_HOST}
            GOTRUE_SMTP_PORT: ${SMTP_PORT}
            GOTRUE_SMTP_USER: ${SMTP_USER}
            GOTRUE_SMTP_PASS: ${SMTP_PASS}

            GOTRUE_DISABLE_SIGNUP: 'false'
            GOTRUE_SITE_URL: localhost
            GOTRUE_MAILER_AUTOCONFIRM: 'true'
            GOTRUE_LOG_LEVEL: DEBUG
            GOTRUE_OPERATOR_TOKEN: ${OPERATOR_TOKEN}
            DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/postgres?sslmode=disable'


        caproverExtra:
            containerHttpPort: '8080'
    # MariaDB
    $$cap_appname-db:
        image: mariadb:10
        environment: # Need to finish
            VAR: '$$cap_variable'
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}




        volumes:
            - '$$cap_appname-db:/var/lib/mysql'
        # ports:
        #     - '3306'
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: '$$cap_gotrue_jwt_secret'
          label: JWT Secret
          defaultValue: '$$cap_gen_random_hex(32)'
          description: Secret string for signing JWTs. Must be more than 32 characters.
          validRegex: 'Not yet valid regex'
        
        - id: '$$cap_gotrue_jwt_exp'
          label: JWT Expiration
          defaultValue: 3600
          description: Time between JWT signing and expiration in seconds.
          validRegex: 'Not yet valid regex'
        
    instructions:
        start: |-
            GoTrue is an API developed by Netlify to handle user authentication. This is the version used by supabase.io.
            More details: https://github.com/supabase/gotrue
        end: |-
            GoTrue has been successfully deployed!
    displayName: Supabase GoTrue
    isOfficial: false
    description: IN DEVELOPMENT | An open source authentication system developed by Netlify, forked by Supabase.
    documentation: See https://github.com/supabase/gotrue
