captainVersion: 4
caproverOneClickApp:
#     variables:
#         - label: HTTP Port
#           description: This is the HTTP port to access appwrite
#           defaultValue: '8000'
#           id: $$cap_http_port
    instructions:
        start: |-
            A free, open source, and selfhostable Discord compatible chat, voice and video platform.
        end: |-
            Fosscord has been successfully deployed! Be sure to activate (or better yet, enforce) https access for $$cap_appname. 
    displayName: Fosscord
    isOfficial: false
    description: A free, open source, and selfhostable Discord compatible chat, voice and video platform.
    documentation: https://docs.fosscord.com/
########
services:
    $$cap_appname-db:
        image: mongo:latest
        volumes:
            - $$cap_appname-db:/data/db
        restart: unless-stopped
    $$cap_appname-api:
        image: fosscord/api
        depends_on:
            - $$cap_appname-db
        environment:
            MONGO_URL=mongodb://$$cap_appname-db/fosscord?readPreference=secondaryPreferred
    $$cap_appname-gateway:
        image: fosscord/gateway
        depends_on:
            - $$cap_appname-db
        environment:
            MONGO_URL=mongodb://$$cap_appname-db/fosscord?readPreference=secondaryPreferred
